# Generated by Django 3.0.7 on 2020-06-12 04:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('poster_path', models.CharField(max_length=150)),
                ('movie_id', models.IntegerField()),
                ('backdrop_path', models.CharField(max_length=150)),
                ('voteavg', models.IntegerField()),
                ('overview', models.TextField()),
                ('release_date', models.CharField(max_length=50)),
                ('like_users', models.ManyToManyField(blank=True, related_name='like_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('gen_users', models.ManyToManyField(blank=True, related_name='like_gens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
